### ISSUE TITLE
If you can please add links to the datasets

### ISSUE THREAD

**Issue by Danzip** [Jungjee/DcaseNet#7]
Can you also add in the readme how you need the directory tree to look like? Those datasets need to be extracted and they have a certain directory tree can you add in the readme an example of how it should like?

**Comment by Jungjee** [comment]
Hi, filetree is available [here](https://github.com/Jungjee/DcaseNet/tree/master/dataset_filetrees)

**Comment by Jungjee** [comment]
all three datasets should be under one root folder :)

**Comment by Danzip** [comment]
thank you very much

**Comment by Danzip** [comment]
I'm sorry but i looked in the SED file-tree and i cant figure out what all those files are the .npy and the. csv all i have from the site is the wav files can you add a link? or explain?
i am getting the error in the pic
![Screenshot from 2021-02-16 16-57-33](https://user-images.githubusercontent.com/34044636/108080103-31462880-7078-11eb-8f0d-99010c7beaf8.png)
i put the wav files in the feat_label folder like so /hdd/data/dcase_2020_task3_extracted/feat_label/foa_dev
foa_dev contains all of the wavs

**Comment by Jungjee** [comment]
Hi, can you check below things? you can ignore .npy files since they belong to different experiments. I should remove them in this repo. 
The basic is that 'h5' files are made using the original 'wav' files.

1. if files with 'h5' extension are created under 'log_mel_spec_label'?
2. whether     [this line](https://github.com/Jungjee/DcaseNet/blob/ddebdcf21c9e821c6b550bc819e39b417c6ab6f9/main.py#L47) is successfully executed

In my opinion, error occurred because the preprocessing wasn't executed correctly
